name: Python Calculator Binaries CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set Up and Uploads Calculator Windows Executable/Binaries
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f ./calculator/requirements.txt ]; then pip install -r ./calculator/requirements.txt; fi
        pip install pyinstaller
    - name: Create Executable/Binaries
      run: |
        python -m PyInstaller ./calculator/calculator.py --onefile --noconsole --icon=./calculator/calculator.ico
    - name: Upload assets to a Release
      uses: AButler/upload-release-assets@v3.0
      with:
          files: "*.exe"
          repo-token: ${{ secrets.GITHUB_TOKEN }}